name: Deploy to EC2

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: SSH into EC2 and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }} 
        key: ${{ secrets.SSH_PRIVATE_KEY }} 
        script: |
          sudo apt-get update && sudo apt-get install -y python3 python3-pip python3-venv git nginx

          # Clone the repository
          git clone https://github.com/movvamanoj/OnlineVoting-Django.git
          cd OnlineVoting-Django

          # Set up virtual environment
          python3 -m venv venv
          source venv/bin/activate

          # Install Python dependencies
          pip install -r requirements.txt

          # Configure Django settings
          # Assuming your settings are already configured for production

          # Set up Gunicorn
          pip install gunicorn

          # Collect static files
          python manage.py collectstatic --noinput

          # Perform database migrations
          python manage.py migrate

          # Restart Gunicorn service
          sudo systemctl restart gunicorn

          # Configure Nginx
          sudo cp deploy/nginx.conf /etc/nginx/sites-available/django
          sudo ln -s /etc/nginx/sites-available/django /etc/nginx/sites-enabled/
          sudo systemctl restart nginx
