name: Deploy Django App

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1  

      - name: SSH into EC2 instance
        uses: nyancatdaffy/ssh-action@v2
        with:
          host: ${{ secrets.EC2_HOST }}  
          username: ${{ secrets.EC2_USER }} 
          key: ${{ secrets.PRIVATE_SSH_KEY }}  
          script: |
            # Update paths based on your project structure
            cd /var/www/onlinevoting  # Assuming your project directory

            # Deployment Script
            git pull origin main
            sudo apt update
            sudo apt install python3-pip -y 
            pip install -r requirements.txt
            python manage.py collectstatic  # Assuming you have static files

            # Migrate database (replace with your command if different)
            python manage.py migrate

            # Service restart commands (replace with your specific commands)
            sudo systemctl restart nginx
            sudo systemctl restart gunicorn  

      - name: Deploy complete
        run: echo "Deployment Successful!"
