name: Deploy Django Project

on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install dependencies and setup environment
      run: |
        sudo apt update -y
        sudo apt install -y git python3 python3-pip
        sudo pip3 install virtualenv
        
        git clone https://github.com/movvamanoj/OnlineVoting-Django.git
        cd OnlineVoting-Django
        python3 -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
        
        # Perform any additional setup steps here
        
        python manage.py migrate
        python manage.py collectstatic --noinput

    - name: Deploy code to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd OnlineVoting-Django
          git pull origin main
          source venv/bin/activate
          python manage.py migrate
          python manage.py collectstatic --noinput
          sudo systemctl restart gunicorn
