name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install python3-pip python3-venv -y
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Deploy code to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd OnlineVoting-Django
            git pull origin main
            source venv/bin/activate
            python manage.py migrate
            python manage.py collectstatic --noinput
            sudo systemctl restart gunicorn
