name: Deploy Django Project

on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: '20'

    steps:
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies and setup environment
      run: |
        sudo apt update -y
        sudo apt install -y git python3 python3-pip
        sudo pip3 install virtualenv
        
        git clone https://github.com/movvamanoj/OnlineVoting-Django.git
        cd OnlineVoting-Django
        python3 -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

        python manage.py migrate
        python manage.py collectstatic --noinput

    - name: Deploy code to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd OnlineVoting-Django
          git pull origin main
          source venv/bin/activate
          python manage.py migrate
          python manage.py collectstatic --noinput
          sudo systemctl restart gunicorn
