name: Deploy Django Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies and setup environment
      run: |
        sudo apt update -y  # Update package index
        sudo apt install -y git python3 python3-pip  # Install Git and Python
        sudo pip3 install virtualenv  # Install virtualenv
        
        git clone https://github.com/movvamanoj/OnlineVoting-Django.git  # Clone your Django project
        cd OnlineVoting-Django  # Navigate to your Django project directory
        python3 -m venv venv  # Create a virtual environment
        source venv/bin/activate  # Activate the virtual environment
        pip install -r requirements.txt  # Install project dependencies

        python manage.py migrate  # Run Django migrations
        python manage.py collectstatic --noinput  # Collect static files

    - name: Deploy code to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd ~/OnlineVoting-Django  # Adjust to the correct path of your Django project
          git pull origin main
          source venv/bin/activate
          python manage.py migrate
          python manage.py collectstatic --noinput
          sudo systemctl restart gunicorn

